# Common versions
arch: "linux-amd64"
prometheus_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

# Common Patroni settings
patroni_scope: demo
patroni_api_port: 8008
patroni_api_ssl_port: 8443
patroni_ttl: 30
patroni_loop_wait: 10
patroni_retry_timeout: 10
patroni_max_lag: 1048576
patroni_use_pg_rewind: true
patroni_use_slots: true
patroni_config: "/etc/patroni.yml"

# etcd settings
etcd_client_port: 2379
clean_etcd: false
etcd_cluster_formation: true
etcd_clean_data: false

# PostgreSQL settings
clean_postgresql: false
postgresql_clean_data: false

# PostgreSQL settigns
pg_version: 16
data_dir: "/var/lib/postgresql/{{ pg_version }}/main"
postgresql_version: 16
postgresql_encoding: UTF8
postgresql_port: 5432
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_dir: "/usr/lib/postgresql/{{ postgresql_version }}/bin"

# SSL/TLS settings
ssl_ca_cert: "/etc/postgresql/certs/root.crt"
ssl_server_cert: "/etc/postgresql/certs/server.crt"
ssl_server_key: "/etc/postgresql/certs/server.key"
ssl_client_cert_dir: "/home/postgres/certs"
ssl_patroni_client_cert_dir: "/home/postgres/patroni-certs"
postgresql_ssl_min_protocol: "TLSv1.2"
postgresql_ssl_prefer_server_ciphers: "on"

# PostgreSQL users
postgresql_superuser_name: postgres
postgresql_superuser_password: password
postgresql_replication_user: replicator
postgresql_replication_password: password
postgresql_replication_auth_method: md5
postgresql_pma_user_password: password

# PostgreSQL params
postgresql_max_connections: 100
postgresql_shared_buffers: 256MB
postgresql_wal_level: replica
postgresql_shared_preload_libraries: "pg_stat_statements, auto_explain"

# Additional PostgreSQL params (optional)
postgresql_custom_parameters:
  max_worker_processes: 8
  max_wal_senders: 10
  wal_keep_segments: 32

# Additional pg_hba.conf rules (optional)
# postgresql_additional_pg_hba:

# PgBouncer params
pgbouncer_listen_port: 6432

# HAProxy params
haproxy_config: "/etc/haproxy/haproxy.cfg"
haproxy_ssl_cert: "/etc/haproxy/certs/patroni.pem"

# Nginx params
nginx_ssl_port: 9443
nginx_ssl_cert: "/etc/nginx/ssl/nginx.crt"
nginx_ssl_key: "/etc/nginx/ssl/nginx.key"

# Cluster variables
cluster_vip_1: 192.168.64.100

# External network access
external_networks:
  - "192.168.0.0/24"
