- name: Install dependencies via apt
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-psycopg2
      - wget
      - gnupg
    update_cache: true

- name: Adding GPG-key PostgreSQL
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/trusted.gpg.d/postgresql.asc
    mode: '0644'

- name: Adding apt repository PostgreSQL
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
    state: present
    filename: "pgdg"

- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install PostgreSQL {{ pg_version }}
  ansible.builtin.apt:
    name: postgresql-{{ pg_version }}
    state: present
    force: yes
  environment:
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"

- name: Install patroni
  ansible.builtin.pip:
    name: patroni[etcd]

- name: Stop PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: stopped
    enabled: false

- name: Create config Patroni
  ansible.builtin.template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
    mode: '0644'

- name: Clean PostgreSQL data directory if needed
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: absent
  when: postgresql_clean_data is defined and postgresql_clean_data | bool

- name: Clean Patroni data from etcd if needed
  ansible.builtin.shell: |
    etcdctl --endpoints=http://{{ ansible_host }}:2379 rm /service/{{ patroni_scope }} --recursive
  ignore_errors: true
  when: postgresql_clean_data is defined and postgresql_clean_data | bool

- name: Set owner of data directory PostgreSQL
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
    recurse: true

- name: Create patroni logs directory
  ansible.builtin.file:
    path: /var/log/patroni
    state: directory
    mode: '0755'

- name: Create systemd unit for Patroni
  ansible.builtin.template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    mode: '0644'

- name: Create config for patroni logrotate
  ansible.builtin.copy:
    dest: /etc/logrotate.d/patroni
    mode: '0644'
    content: |
      /var/log/patroni/patroni.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          create 0640 postgres postgres
      }

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Patroni systemd unit
  ansible.builtin.systemd:
    name: patroni
    state: restarted
    enabled: true

- name: Copy Patroni CA certificate to system certificate store
  ansible.builtin.copy:
    src: /etc/patroni/certs/root.crt
    dest: /usr/local/share/ca-certificates/patroni-ca.crt
    remote_src: true
    mode: '0644'

- name: Update CA certificates
  ansible.builtin.shell: update-ca-certificates
  args:
    creates: /etc/ssl/certs/patroni-ca.pem

- name: Verify Patroni certificates
  ansible.builtin.shell: |
    openssl x509 -in /etc/patroni/certs/patroni.crt -text -noout | grep -A 10 "Subject Alternative Name"
  register: patroni_cert_info
  changed_when: false

- name: Display Patroni certificate info
  ansible.builtin.debug:
    var: patroni_cert_info.stdout_lines

- name: Wait for PostgreSQL to be ready
  ansible.builtin.wait_for:
    port: "{{ postgresql_port }}"
    host: "{{ ansible_host }}"
    delay: 10
    timeout: 60

- name: Create pma_user if not exists
  ansible.builtin.postgresql_user:
    login_host: "{{ ansible_host }}"
    login_user: "{{ postgresql_superuser_name }}"
    login_password: "{{ postgresql_superuser_password }}"
    name: pma_user
    password: "{{ postgresql_pma_user_password }}"
    role_attr_flags: "SUPERUSER"
    state: present
  when: inventory_hostname == groups['promoters'][0]  # Only run on first node
