- name: Install etcd via apt
  ansible.builtin.apt:
    name:
      - etcd
    update_cache: true

- name: Create etcd configuration directory
  ansible.builtin.file:
    path: /etc/etcd
    state: directory
    mode: '0755'

- name: Create etcd data directory
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    mode: '0755'
    owner: etcd
    group: etcd

- name: Clean etcd data directory if requested
  ansible.builtin.file:
    path: /var/lib/etcd
    state: absent
  when: etcd_clean_data | bool
  notify: restart etcd

- name: Recreate etcd data directory after cleanup
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    mode: '0755'
    owner: etcd
    group: etcd
  when: etcd_clean_data | bool

- name: Configure etcd
  ansible.builtin.template:
    src: etcd.conf.yml.j2
    dest: /etc/etcd/etcd.conf.yml
    mode: '0644'
    owner: etcd
    group: etcd
  notify: restart etcd

- name: Configure etcd systemd service
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: '0644'
  notify: restart etcd

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and enable etcd service
  ansible.builtin.systemd:
    name: etcd
    state: started
    enabled: true

- name: Wait for etcd to be ready
  ansible.builtin.wait_for:
    port: 2379
    host: "{{ ansible_host }}"
    delay: 10
    timeout: 60

- name: Check if etcd is already running
  ansible.builtin.systemd:
    name: etcd
  register: etcd_status

- name: Display etcd status
  ansible.builtin.debug:
    msg: "etcd on {{ inventory_hostname }}: {{ etcd_status.status.ActiveState }}"

- name: Check etcd cluster health
  ansible.builtin.shell: |
    etcdctl --endpoints=http://{{ ansible_host }}:2379 cluster-health
  register: cluster_health
  changed_when: false
  when: etcd_status.status.ActiveState == "active"

- name: Display cluster health
  ansible.builtin.debug:
    msg: "{{ cluster_health.stdout_lines }}"
  when: etcd_status.status.ActiveState == "active"

- name: List etcd members
  ansible.builtin.shell: |
    etcdctl --endpoints=http://{{ ansible_host }}:2379 member list
  register: member_list
  changed_when: false
  when: etcd_status.status.ActiveState == "active"

- name: Display member list
  ansible.builtin.debug:
    msg: "{{ member_list.stdout_lines }}"
  when: etcd_status.status.ActiveState == "active"
